config/routes.rb
Rails.application.routes.draw do
  root to: "home#sign_in"

  match "/auth/:provider/callback" => "sessions#create", via: [:get, :post]
  match "/signout" => "sessions#destroy", :as => :signout, via: [:delete]
  match "/auth/failure" => "home#sign_in", via: [:get, :post]

  match "/contacts/:visit_id/:hosting_id" => "contacts#create", via: [:post]

  get 'privacy_policy', to: 'policies#facebook'

  resource :contacts, only: [:create]

  resources :visits, only: [:create, :destroy, :update, :show, :edit]

  resources :hostings, only: [:create, :destroy, :edit, :update]

  resources :users, only: [:edit, :show, :update, :destroy] do
    member do
      get :confirm_email
      get :unsubscribe
      delete :do_unsubscribe
    end

    resources :visits, only: [:new]
    resources :hostings, only: [:new]
  end

  get "/pages/:page" => "pages#show"
  get "five_hundred" => "home#five_hundred"
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  validates_date :start_date, on: :create, presence: true
  validate :validate_start_date_is_not_in_the_past, if: :start_date

  validates_date :end_date, on: :create, on_or_after: :start_date
  validates :zipcode, zipcode: { country_code: :es }

  belongs_to :user
  has_many :contacts

  after_validation :geocode

  geocoded_by :zipcode do |visit, results|
    if geo = results.first
      visit.city = geo.city
      visit.state = geo.state
      visit.latitude = geo.latitude
      visit.longitude = geo.longitude
    else
      visit.errors.add(:base, "Unknown Zip Code") unless visit.zipcode.nil?
    end
  end

  acts_as_paranoid

  def validate_start_date_is_not_in_the_past
    # We compare to yesterday because user's "today" may be yesterday in UTC.  But
    # we're OK since datepicker in javascript enforces using the user's time zone.
    errors.add(:start_date, :in_past) unless start_date >= Date.current - 1.day
  end

  def available_hostings(current_user)
    available_hostings = Hosting
      .near(self, 75, order: 'distance')
      .where("start_date <= ?", self.end_date)
      .where("end_date >= ?", self.start_date)

    if Rails.env.production? or Rails.env.staging?
      # :nocov:
      return available_hostings.where("host_id != (?)", self.user_id)
      # :nocov:
    else
      return available_hostings
    end
  end

  def start_and_end_dates
    starting = start_date.strftime("%m/%d/%y")
    ending = end_date.strftime("%m/%d/%y")

    "#{starting} - #{ending}"
  end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :find_visit, only: [:show, :edit, :update, :destroy]
  before_action :ensure_current_user_is_visitor, only: [:show, :edit, :update, :destroy]

  def new
    @visit ||= Visit.new(user_id: params[:user_id])
  end

  def create
    @visit = Visit.new(visit_params)
    @visit.user_id = current_user.id

    if @visit.save
      redirect_to visit_url(@visit), notice: "Visit created!"
    else
      flash.now[:errors] = @visit.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    if @visit.update(visit_params)
      redirect_to visit_url(@visit), notice: "Visit updated"
    else
      flash.now[:errors] = @visit.errors.full_messages
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @visit.destroy
      redirect_to user_url(current_user), notice: "Visit canceled"
    else
      flash.now[:errors] = @visit.errors.full_messages
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def visit_params
    params
      .require(:visit)
      .permit(:zipcode, :num_travelers, :start_date, :end_date)
  end

  def find_visit
    @visit = Visit.find_by_id(params[:id])
    if @visit.nil?
      flash[:notice] = "Oops! That visit has been canceled."
      redirect_to user_url(current_user)
    end
  end

  def ensure_current_user_is_visitor
    redirect_to user_url(current_user) unless @visit.user_id == current_user.id
  end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_contact_host_instructions.html.haml
%div
  - if hosting.comment?
    %h3 Message from #{ host_name }:
    %p "#{ hosting.comment }"

  %h3 Contact #{ host_name }
  %p We'll email #{ host_name } your contact info, saying:
  %ul
    %li - You need a place to stay
    %li - Your total number of travelers
    %li - Your arrival/departure dates
    %li - Your name
    %li - Your email address
    %li - Your phone number
  %p Then, #{ host_name } should contact you to work out the details.
  %p We strongly recommend hosts and visitors connect over social media before making any plans.

  = link_to "Send my contact info",
            "/contacts/#{ @visit.id }/#{ hosting.id }",
            method: "POST",
            class: 'btn btn-danger btn-block btn-lg half-bump'

app/views/visits/_empty_visits.html.haml
%header.empty
  %h1 Nobody here, yet.
  %span Save this page and check back often. New hosts sign up every day!

app/views/visits/_hosts.html.haml
- visit.available_hostings(current_user).each_with_index do |hosting, index|
- host_name = hosting.first_name
- heading_id = "heading#{ index }"
- tab_id = "collapse#{ index }"
  - if hosting.has_contact_for?(visit)
    - if hosting.was_contacted_for?(visit)
      - button_text = "✔ Contacted"
    - else
      - button_text = "Will Contact Host Tonight"
    - button_class = "btn-success"
    - button_collapsable = ""
  - else
    - button_text = "Contact"
    - button_class = "btn-info"
    - button_collapsable = "collapse"

  %div.panel

    %div.panel-heading.group{ role: 'tab', id: "#{ heading_id }" }
      %h4.panel-title.left
        %ul
          %li
            %h2 #{ host_name }
          %li
            %span #{ hosting.city || hosting.zipcode } - #{ hosting.distance.round(1) } miles
          %li
            %small Space for #{ hosting.max_guests } in a #{ hosting.decorate.pretty_accomodation_type }
          %li
            %small Available #{ hosting.start_and_end_dates }
      %a{ href: "##{ tab_id }",
          "role" => "button",
          class: "btn btn-md #{ button_class } contact-button right",
          "data-toggle" => "#{ button_collapsable }",
          "data-parent" => "#accordion",
          "aria-expanded" => "false" ,
          "aria-controls" => "#{ tab_id }" } #{ button_text }

    %div.panel-collapse.collapse{"role" => "tabpanel",
                                 id: "#{tab_id}",
                                 "aria-labelledby" => "#{heading_id}",
                                 "aria-expanded" => "false" }
      %div.panel-body
        - unless hosting.has_contact_for?(visit)
          = render 'contact_host_instructions',
            host_name: host_name,
            hosting: hosting,
            visit: @visit
          %a{ href: "##{ tab_id }",
              "role" => "button",
              class: "btn btn-info btn-block btn-lg half-bump",
              "data-toggle" => "#{ button_collapsable }",
              "data-parent" => "#accordion",
              "aria-expanded" => "false" ,
              "aria-controls" => "#{ tab_id }" } Cancel

app/views/visits/_visit_form.html.haml
- action = @visit.persisted? ? "update" : "create"

= form_for @visit, url: { action: action } do |f|
  .form-fields
    .form-group
      = f.label :zipcode, "Where are you going?"
      = f.text_field :zipcode, class: "form-control"
      %small Zip Code near your destination.

    .form-group
      %label What nights are you staying?
      = f.hidden_field :start_date, class: "form-control"
      = f.hidden_field :end_date, class: "form-control"
      %div.datepicker
      %small.dateText Staying over these nights.

    .form-group
      = f.label :num_travelers, "How many total travelers?"
      = f.select :num_travelers,
        options_for_select((1..10).zip(1..10), @visit.num_travelers || nil),
        {},
        { class: 'form-control' }
      %small Including yourself.

  = f.submit "Contact Hosts", class: 'btn btn-success btn-block btn-lg'

app/views/visits/edit.html.haml
.user-new-visit
  %div.group
    =link_to("« Back", user_url(current_user), class: 'btn btn-info btn-sm left')
    =link_to("Sign Out", signout_url, method: :delete, class: "btn btn-info btn-sm right")
  %header
    %p.lead Travel

  = render "visit_form"
  = link_to "Delete", visit_path(@visit), method: "DELETE", class: 'btn btn-danger btn-block btn-lg'

app/views/visits/new.html.haml
.user-new-visit
  %div.group
    =link_to("« Back", user_url(current_user), class: 'btn btn-info btn-sm left')
    =link_to("Sign Out", signout_url, method: :delete, class: "btn btn-info btn-sm right")
  %header
    %p.lead Travel

  = render 'visit_form'
  = link_to "Cancel", user_url(current_user), class: 'btn btn-danger btn-block btn-lg'

app/views/visits/show.html.haml
%div.available-hosts
  = render "home/navbuttons"
  - if @visit.available_hostings(current_user).empty?
    = render 'empty_visits'
  - else
    %header
      %h1.hosts-heading Hosts near #{ @visit.city || @visit.zipcode }
      %span Contact any good matches below
    %div.panel-group#accordion{ "role" => 'tablist', "aria-multiselectable" => 'true' }
      = render "hosts", visit: @visit