config/routes.rb
Rails.application.routes.draw do
  root to: "home#sign_in"

  match "/auth/:provider/callback" => "sessions#create", via: [:get, :post]
  match "/signout" => "sessions#destroy", :as => :signout, via: [:delete]
  match "/auth/failure" => "home#sign_in", via: [:get, :post]

  match "/contacts/:visit_id/:hosting_id" => "contacts#create", via: [:post]

  get 'privacy_policy', to: 'policies#facebook'

  resource :contacts, only: [:create]

  resources :visits, only: [:create, :destroy, :update, :show, :edit]

  resources :hostings, only: [:create, :destroy, :edit, :update]

  resources :users, only: [:edit, :show, :update, :destroy] do
    member do
      get :confirm_email
      get :unsubscribe
      delete :do_unsubscribe
    end

    resources :visits, only: [:new]
    resources :hostings, only: [:new]
  end

  get "/pages/:page" => "pages#show"
  get "five_hundred" => "home#five_hundred"
end

app/models/user.rb
class User < ActiveRecord::Base
  include ActionView::Helpers::NumberHelper
  include ActiveModel::Dirty

  MAX_DOMESTIC_PHONE_NUMBER = 12
  MAX_INTERNATIONAL_PHONE_NUMBER = 14

  validate :phone_number_length
  validates :first_name, presence: true, allow_nil: true
  validates :email, presence: true, allow_nil: true, uniqueness: true
  validates :uid, :session_token, presence: true, uniqueness: true
  validates_format_of :email,
    :with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/,
    allow_nil: true
  validate :no_changes_to_email_after_confirmed

  before_create :create_confirmation_token

  after_initialize :ensure_session_token

  has_many :visits, dependent: :destroy

  has_many :hostings, class_name: "Hosting", foreign_key: :host_id, dependent: :destroy

  def self.generate_secure_token
    SecureRandom::urlsafe_base64(16)
  end

  def self.create_with_omniauth(auth)
    if auth["info"]["email"]
      create! do |user|
        user.provider = auth["provider"]
        user.uid = auth["uid"]
        user.email = auth["info"]["email"]
      end
    else
      create! do |user|
        user.provider = auth["provider"]
        user.uid = auth["uid"]
      end
    end
  end

  def phone=(number)
    number = number[1..-1] if number[0] == "1" # Alway remove leading "1".

    if number[0] == "+" # international
      pnumber = number_to_phone(number.gsub(/\D+/, ''))
      super("+" + pnumber)
    else # not international
      pnumber = number_to_phone(number.gsub(/\D+/, ''))
      super(pnumber)
    end
  end

  def phone_number_length
    return if phone.nil?
    if phone.size > MAX_DOMESTIC_PHONE_NUMBER
      if phone[0] == '+' # international +DD XXX XXXXXX (2,3,6 chars)
        if phone.size > MAX_INTERNATIONAL_PHONE_NUMBER
          self.errors.add(:phone, "number is too long: #{phone}")
        elsif phone.size < MAX_INTERNATIONAL_PHONE_NUMBER
          self.errors.add(:phone, "number is too short: #{phone}")
        end
      else # not international
        self.errors.add(:phone, "number is too long: #{phone}")
      end
    elsif phone.size < MAX_DOMESTIC_PHONE_NUMBER
      self.errors.add(:phone, "number is too short: #{phone}")
    end
  end

  def no_changes_to_email_after_confirmed
    if email_changed? && email_confirmed && !email_confirmed_changed?
      self.errors.add(:email, "cannot be changed after being confirmed")
    end
  end

  def reset_session_token!
    self.session_token ||= self.class.generate_secure_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= self.class.generate_secure_token
  end

  def create_confirmation_token
    self.confirm_token ||= self.class.generate_secure_token
  end

  def email_activate
    self.email_confirmed = true
    save!(validate: false)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_current_user_is_user, only: [:edit, :show, :update, :destroy]
  skip_before_action :require_complete_profile, only: [:edit, :update, :confirm_email, :unsubscribe, :do_unsubscribe]
  skip_before_action :require_current_user, only: [:confirm_email, :unsubscribe, :do_unsubscribe]
  decorates_assigned :user

  def edit
  end

  def show
  end

  def unsubscribe
    @user = User.find_by_confirm_token(params[:id])

    if not @user
      flash[:errors] = ["Something went wrong, maybe you are already unsubscribed?  If you are having trouble please admin@hillarybnb.com"]
      redirect_to root_url
    end
  end

  def update
    if @user.update(user_params)
      if @user.email_confirmed
        redirect_to user_url(@user),
          notice: "Account updated"
      else
        UserMailer.registration_confirmation(@user).deliver_now
        sign_out!
        redirect_to root_url,
          notice: "Email confirmation sent, check your email for instructions"
      end

    else
      flash[:errors] = @user.errors.full_messages
      redirect_to edit_user_url(@user)
    end
  end

  def do_unsubscribe
    @user = User.find_by_confirm_token(params[:id])

    if @user
      if @user.destroy
        redirect_to root_url,
          notice: "OK, your account is deleted."
      else
        flash[:errors] = @user.errors.full_messages
        redirect_to root_url
      end
    else
      flash[:errors] = ["Something went wrong, maybe you are already unsubscribed?  If you are having trouble please admin@hillarybnb.com"]
      redirect_to root_url
    end
  end

  def destroy
    if @user.destroy
      redirect_to root_url,
        notice: "OK, your account is deleted."
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to edit_user_url(@user)
    end
  end

  def confirm_email
    @user = User.find_by_confirm_token(params[:id])

    if @user
      @user.email_activate
      sign_in!(@user)

      UserMailer.welcome_email(@user)

      redirect_to user_url(@user)
    else
      flash[:errors] = ["Sorry, something went wrong.  Please try again, or email us at admin@hillarybnb.com for help."]
      redirect_to root_url
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :phone, :email)
  end

  def ensure_current_user_is_user
    @user = User.find(params[:id])
    redirect_to user_url(current_user) unless @user == current_user
  end
end

app/views/users/edit.html.haml
- button_text = @user.email_confirmed ? 'Save' : 'Confirm Email'

.profile-page
  %div.group
    =link_to("« Home", user_url(current_user), class: 'btn btn-info btn-sm left')
    =link_to("Sign Out", signout_url, method: :delete, class: "btn btn-info btn-sm right")
  %p.lead.text-center Profile

  = form_for @user, url: { action: 'update' } do |f|
    .form-fields
      .form-group
        = f.label :email, 'Your email address:'
        = f.email_field :email, placeholder: 'Email', readonly: @user.email_confirmed, class: 'form-control'
        %span We'll send you email notifications.

      .form-group
        = f.label :first_name, 'What\'s your first name?'
        = f.text_field :first_name, placeholder: 'First name', class: 'form-control'
      .form-group
        = f.label :phone, 'What\'s your phone number?'
        = f.phone_field :phone, placeholder: 'Phone number', class: 'form-control'
        %span We'll send this when you contact someone.

      .form-group
        = f.submit button_text, class: 'btn btn-success btn-block btn-lg'
        - if @user.email_confirmed
          = link_to "Cancel", user_url(current_user), class: 'btn btn-danger btn-lg btn-block'
        - else
          = link_to "Cancel", root_url, class: 'btn btn-danger btn-lg btn-block'

  - if @user.email_confirmed

    = button_to 'Delete Account',
      { action: 'destroy', id: @user.id },
        class: 'btn btn-default btn-block btn-lg',
        method: 'delete',
        data: { confirm: "Are you sure? This will permanently delete your account." }

app/views/users/show.html.haml
%div.user-home
  %div.group
    =link_to("« Profile", edit_user_url(current_user), class: 'btn btn-info btn-sm left')
    =link_to("Sign Out", signout_url, method: :delete, class: "btn btn-info btn-sm right")

  %header.heading
    %p.lead.text-center.bump
      %img.img-logo{src: image_url(site_image_name)}

  %section.user-travels
    %header
      = link_to 'Find A Host', new_user_visit_url(user), class: 'btn btn-primaryblue btn-block btn-lg'
      %span On the road for Hillary?
    - unless user.visits.empty?
      %ul
        - user.visits.each do |visit|
          %li
            = link_to edit_visit_url(visit), class: ['btn btn-default btn-block btn-lg'], role: 'button' do
              = visit.location
              .small-details
                = visit.date

  %section.user-hostings
    %header
      = link_to 'I Can Host', new_user_hosting_url(user), class: 'btn btn-lightblue btn-block btn-lg'
      %span Have room to share?
    - unless user.hostings.empty?
      %ul
        - user.hostings.each do |hosting|
          %li
            = link_to edit_hosting_url(hosting), class: ['btn btn-default btn-block btn-lg'], role: 'button' do
              = hosting.location
              .small-details
                = hosting.short_details

      .text-center.share
        = link_to '#', class: 'btn btn-share facebook-share' do
          %i.fa.fa-facebook{ :type => 'button', :aria_hidden => 'true' }
          share
        = link_to 'https://twitter.com/intent/tweet' + |
                  '?hashtags=Clinton,HillaryBNB' + |
                  '&text=Get involved with @HillaryClinton by offering campaign volunteers a place to stay!' + |
                  '&url=http://HillaryBNB.com', |
                  class: 'btn btn-share twitter-share' do
          %i.fa.fa-twitter{ :type => 'button', :aria_hidden => 'true' }
          tweet
        %span Thanks for hosting!
%footer

app/views/users/unsubscribe.html.haml
.profile-page
  %p.lead.text-center Unsubscribe

  %div{:style => 'text-align: center'} <br>Unsubscribing will delete your account, including all active hostings and visits.<br>You will no longer receive any emails from HillaryBNB.<br><br>
  = button_to 'Click here to unsubscribe',
    { action: 'do_unsubscribe', id: @user.confirm_token },
      class: 'btn btn-danger btn-block btn-lg',
      method: 'delete'