config/routes.rb
Rails.application.routes.draw do
  root to: "home#sign_in"

  match "/auth/:provider/callback" => "sessions#create", via: [:get, :post]
  match "/signout" => "sessions#destroy", :as => :signout, via: [:delete]
  match "/auth/failure" => "home#sign_in", via: [:get, :post]

  match "/contacts/:visit_id/:hosting_id" => "contacts#create", via: [:post]

  get 'privacy_policy', to: 'policies#facebook'

  resource :contacts, only: [:create]

  resources :visits, only: [:create, :destroy, :update, :show, :edit]

  resources :hostings, only: [:create, :destroy, :edit, :update]

  resources :users, only: [:edit, :show, :update, :destroy] do
    member do
      get :confirm_email
      get :unsubscribe
      delete :do_unsubscribe
    end

    resources :visits, only: [:new]
    resources :hostings, only: [:new]
  end

  get "/pages/:page" => "pages#show"
  get "five_hundred" => "home#five_hundred"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :require_current_user
  skip_before_action :require_complete_profile
  def sign_in
  end

  def five_hundred
    puts "YO YO YO"
    puts 1/0
    render text: "this is it"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_navbuttons.html.haml
%div.group
  =link_to("« Home", user_url(current_user), class: 'btn btn-info btn-sm left')
  =link_to("Sign Out", signout_url, method: :delete, class: "btn btn-info btn-sm right")

app/views/home/sign_in.html.haml
.sign-in
  %p.lead.text-center.bump
    %img.img-logo{src: image_url(site_image_name)}

  %section.instructions
    %p.lead.text-center How Home Sharing Works
    %table.bump
      %tr
        %td
          %span.big-number 1
        %td Fill out a quick user profile using your Facebook or Google login.
      %tr
        %td
          %span.big-number 2
        %td Create a travel request or hosting offer.

      %tr
        %td
          %span.big-number 3
        %td Travelers send their contact info and trip details to nearby hosts.
      %tr
        %td
          %span.big-number 4
        %td Hosts confirm by phone or email.
  %hr.bump

  %section.sign-up.bump
    %p.lead.text-center Sign In Using...
    = link_to "Facebook", "/auth/facebook", {class: 'bump btn btn-primaryblue btn-block btn-lg'}
    = link_to "Google", "/auth/google_oauth2", {class: 'btn btn-lightblue btn-block btn-lg'}