config/routes.rb
Rails.application.routes.draw do
  root to: "home#sign_in"

  match "/auth/:provider/callback" => "sessions#create", via: [:get, :post]
  match "/signout" => "sessions#destroy", :as => :signout, via: [:delete]
  match "/auth/failure" => "home#sign_in", via: [:get, :post]

  match "/contacts/:visit_id/:hosting_id" => "contacts#create", via: [:post]

  get 'privacy_policy', to: 'policies#facebook'

  resource :contacts, only: [:create]

  resources :visits, only: [:create, :destroy, :update, :show, :edit]

  resources :hostings, only: [:create, :destroy, :edit, :update]

  resources :users, only: [:edit, :show, :update, :destroy] do
    member do
      get :confirm_email
      get :unsubscribe
      delete :do_unsubscribe
    end

    resources :visits, only: [:new]
    resources :hostings, only: [:new]
  end

  get "/pages/:page" => "pages#show"
  get "five_hundred" => "home#five_hundred"
end

app/models/hosting.rb
class Hosting < ActiveRecord::Base
  enum accomodation_type: [ :home, :hotel ]

  validates :max_guests, presence: true
  validates :zipcode, zipcode: { country_code: :es }
  validates :comment, length: { maximum: 5000 }
  validates :accomodation_type, presence: true

  validates_date :start_date, on: :create, presence: true
  validate :validate_start_date_is_not_in_the_past, if: :start_date
  validates_date :end_date, on: :create, on_or_after: :start_date

  acts_as_paranoid

  belongs_to :host, class_name: "User", foreign_key: :host_id
  has_many :contacts

  after_validation :geocode, :if => lambda{ |obj| obj.zipcode_changed? }

  geocoded_by :zipcode do |hosting, results|
    if geo = results.first
      hosting.city = geo.city
      hosting.state = geo.state
      hosting.latitude = geo.latitude
      hosting.longitude = geo.longitude
    else
      hosting.errors.add(:base, "Unknown Zip Code") unless hosting.zipcode.nil?
    end
  end

  def first_name
    host.first_name
  end

  def was_contacted_for?(visit)
    Contact.where(visit_id: visit.id, hosting_id: self.id).first.sent.present?
  end

  def has_contact_for?(visit)
    Contact.exists?(visit_id: visit.id, hosting_id: self.id)
  end

  def validate_start_date_is_not_in_the_past
    # We compare to yesterday because user's "today" may be yesterday in UTC.  But
    # we're OK since datepicker in javascript enforces using the user's time zone.
    errors.add(:start_date, :in_past) unless start_date >= Date.current - 1.day
  end

  def start_and_end_dates
    starting = start_date.strftime("%m/%d/%y")
    ending = end_date.strftime("%m/%d/%y")

    "#{starting} - #{ending}"
  end
end

app/controllers/hostings_controller.rb
class HostingsController < ApplicationController
  before_action :find_hosting, only: [:edit, :update, :destroy]
  before_action :ensure_current_user_is_host, only: [:edit, :update, :destroy]

  def new
    @hosting ||= Hosting.new(host_id: params[:user_id], start_date: nil, end_date: nil)
  end

  def create
    @hosting = Hosting.new(hosting_params)
    @hosting.host_id = current_user.id

    if @hosting.save
      redirect_to user_url(current_user),
        notice: "Hosting created! We will email you when a nearby traveler would like to stay with you."
    else
      flash.now[:errors] = @hosting.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @hosting.update(hosting_params)
      redirect_to user_url(current_user),
        notice: "Hosting updated! We will email you when a nearby traveler would like to stay with you."
    else
      flash.now[:errors] = @hosting.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def destroy
    if @hosting.destroy
      redirect_to user_url(current_user), notice: "Hosting canceled"
    else
      flash.now[:errors] = @hosting.errors.full_messages
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def hosting_params
    params
      .require(:hosting)
      .permit(:zipcode, :max_guests, :comment, :accomodation_type, :start_date, :end_date)
  end

  def find_hosting
    @hosting = Hosting.find_by_id(params[:id])
    if @hosting.nil?
      flash[:notice] = "Oops! That hosting has been canceled."
      redirect_to user_url(current_user)
    end
  end

  def ensure_current_user_is_host
    redirect_to user_url(current_user) unless @hosting.host_id == current_user.id
  end
end

app/helpers/hostings_helper.rb
module HostingsHelper
end

app/views/hostings/_hosting_form.html.haml
- action = @hosting.persisted? ? "update" : "create"

= form_for @hosting, url: { action: action } do |f|
  .form-fields
    .form-group
      = f.label :zipcode, "Where are you located?"
      = f.text_field :zipcode, class: 'form-control', placeholder: "5-digit zip code"
      %span.hosting Your zip code.

    .form-group
      = f.label :accomodation_type, "What kind of accomodation are you offering?"
      .multiline-radio
        = f.label :accomodation_type_home, :display => 'inline-block' do 
          = f.radio_button :accomodation_type, 'home', :checked => true
          %span.hosting Room or bed in my home
        = f.label :accomodation_type_home, :display => 'inline-block' do 
          = f.radio_button :accomodation_type, 'hotel'
          %span.hosting Hotel room or other accommodations

    .form-group
      = f.label :max_guests, "How many can you host?"
      = f.select :max_guests,
        options_for_select((1..10).zip(1..10), @hosting.max_guests || nil),
        {},
        {class: 'form-control'}
      %span.hosting Preferred maximum number of guests.

    .form-group
      %label What nights can you host?
      = f.hidden_field :start_date, class: "form-control"
      = f.hidden_field :end_date, class: "form-control"
      %div.datepicker
      %span.dateText Hosting these nights

    .form-group
      = f.label :comment, "Please share any additional information about your accommodations:"
      = f.text_field :comment, class: 'form-control'
      %span.hosting e.g. number of available beds, cost per person in shared hotel room or rental house, or accessible hours.

  = f.submit "Save", class: 'btn btn-success btn-block btn-lg'

app/views/hostings/edit.html.haml
.user-new-hosting
  %div.group
    =link_to("« Back", user_url(current_user), class: 'btn btn-info btn-sm left')
    =link_to("Sign Out", signout_url, method: :delete, class: "btn btn-info btn-sm right")
  %header
    %p.lead Host

  = render 'hosting_form'
  = link_to "I Can't Host", hosting_path(@hosting), method: :delete, class: 'btn btn-danger btn-block btn-lg'

app/views/hostings/new.html.haml
.user-new-hosting
  %div.group
    =link_to("« Back", user_url(current_user), class: 'btn btn-info btn-sm left')
    =link_to("Sign Out", signout_url, method: :delete, class: "btn btn-info btn-sm right")
  %header
    %p.lead Host

  = render 'hosting_form'
  = link_to "Cancel", user_url(current_user), class: 'btn btn-danger btn-block btn-lg'